# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: stuck in cyberspace
email: innovative.disruption@gmail.com
url: "http://stuckincyber.space"
description: Welcome to the homebase of Chelsea Palmer (aka msGNU)

# the subpath of your site, e.g. /blog
baseurl: ""
twitter_username: IMmsGNU
github_username:  chiselinc
linkedin_username: Chelsea Palmer
linkedin_url: https://ca.linkedin.com/in/chelsea-palmer-79280ab5
markdown: kramdown
